[2022-06-13 13:46:43,342] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ingest_data.save_data_task scheduled__2022-06-12T21:01:00+00:00 [queued]>
[2022-06-13 13:46:43,376] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ingest_data.save_data_task scheduled__2022-06-12T21:01:00+00:00 [queued]>
[2022-06-13 13:46:43,377] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-13 13:46:43,377] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-13 13:46:43,378] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-13 13:46:43,432] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): save_data_task> on 2022-06-12 21:01:00+00:00
[2022-06-13 13:46:43,437] {standard_task_runner.py:52} INFO - Started process 218 to run task
[2022-06-13 13:46:43,442] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'ingest_data', 'save_data_task', 'scheduled__2022-06-12T21:01:00+00:00', '--job-id', '1535', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmpq4ik_czb', '--error-file', '/tmp/tmpsi52z6p7']
[2022-06-13 13:46:43,443] {standard_task_runner.py:80} INFO - Job 1535: Subtask save_data_task
[2022-06-13 13:46:43,574] {task_command.py:370} INFO - Running <TaskInstance: ingest_data.save_data_task scheduled__2022-06-12T21:01:00+00:00 [running]> on host DESKTOP-GDPK8BL.localdomain
[2022-06-13 13:46:44,119] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=save_data_task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-12T21:01:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-12T21:01:00+00:00
[2022-06-13 13:46:44,132] {python.py:173} INFO - Done. Returned value was: None
[2022-06-13 13:46:44,157] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=save_data_task, execution_date=20220612T210100, start_date=20220613T114643, end_date=20220613T114644
[2022-06-13 13:46:44,218] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-13 13:46:44,366] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
